# Generated by Django 3.0.6 on 2020-05-25 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Delve_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=10)),
                ('nation_slug', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=255)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delve_form.Position')),
            ],
        ),
    ]
