# Generated by Django 3.0.6 on 2020-05-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delve_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delve_form',
            name='skills',
        ),
        migrations.AddField(
            model_name='delve_form',
            name='skill_html',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delve_form',
            name='skill_javascript',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delve_form',
            name='skill_php',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delve_form',
            name='skill_python',
            field=models.BooleanField(default=False),
        ),
    ]
