# Generated by Django 3.0.6 on 2020-05-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delve_form', '0002_auto_20200525_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='delve_form',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
